# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Approach"
  pageRef = "approach"
  weight = 10

[[main]]
  name = "Software"
  pageRef = "software"
  weight = 20

[[main]]
  name = "Applications"
  pageRef = "applications"
  weight = 30

[[main]]
  name = "Work"
  pageRef = "work"
  weight = 35

[[main]]
  name = "Contact"
  pageRef = "contact"
  weight = 40

[[main]]
  name = "Demo"
  url = "https://demo.pelagia.studio/?server=https%3A%2F%2Fdemoapi.pelagia.studio&username=demo&password=demo"
  weight = 50
  [main.params]
    rel = "noopener noreferrer"
    target = "_blank"

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
  name = "Approach"
  pageRef = "approach"
  weight = 10

[[footer]]
  name = "Software"
  pageRef = "software"
  weight = 20

[[footer]]
  name = "Applications"
  pageRef = "applications"
  weight = 30

[[footer]]
  name = "Work"
  pageRef = "work"
  weight = 35

[[footer]]
  name = "Demo"
  url = "https://demo.pelagia.studio/?server=https%3A%2F%2Fdemoapi.pelagia.studio&username=demo&password=demo"
  weight = 40
  [footer.params]
    rel = "noopener noreferrer"
    target = "_blank"

[[footer]]
  name = "Source"
  url = "https://github.com/Icy-Seas-Co-Laboratory/Pelagia"
  weight = 50
  [footer.params]
    rel = "noopener noreferrer"
    target = "_blank"

[[footer]]
  name = "Privacy"
  pageRef = "privacy"
  weight = 60
